service:
  name: sqs-test-ts
# app and org for use with dashboard.serverless.com
app: sqs-test-ts
org: arjones

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-offline
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
      Resource:
        - Fn::GetAtt: [ sqsTestTsQueue, Arn ]
        - Fn::GetAtt: [ sqsTestTsQueueResult, Arn ]

functions:
  jobSubmit:
    handler: handler.jobSubmit
    events:
      - http:
          method: post
          path: /sqs/jobSubmit
  
  jobResult:
    handler: handler.jobResult
    events:
      - http:
          method: get
          path: /sqs/jobResult

  worker:
      handler: handler.worker
      events:
        - sqs:
            arn:
              Fn::GetAtt:
                - sqsTestTsQueue
                - Arn

resources:
  Resources:
    sqsTestTsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: sqsTestTsQueue
  
    sqsTestTsQueueResult:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: sqsTestTsQueueResult
